In [ ]:
import torch
import torch.nn as nn
import  torch.nn.functional as F

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [ ]:
w_q= torch.Tensor([[-0.35, 0.51, 0.50],
                   [0.36, -0.47, -0.29],
                   [-0.51, -0.14, -0.56]]) #(dim_input , dim_output)
w_k= torch.Tensor([[-0.49, -0.68, 0.18],
                   [-0.44, -0.46, 0.18],
                   [0.07, -0.10, 0.44]])
w_v= torch.Tensor([[-0.41, 0.39, -0.65],
                   [-0.40, -0.07, -0.34],
                   [-0.55, -0.13, -0.29]])
w_o = torch.Tensor([[-0.36, -0.08, 0.32],
                    [0.27, 0.05, 0.15],
                    [-0.05, -0.28, 0.05]])

X = torch.Tensor([[-0.2, 0.0, 0.4]])
q= X@w_q
k= X@w_k
v= X@w_v
o= X@w_o

d=3
score_raw= (q@k.T)/d**0.5

attn_weights = F.softmax(score_raw, dim=-1)
attn_weights

context = attn_weights@v
Y = context @ w_o
Y

tensor([[ 0.0139,  0.0006, -0.0630]])

In [ ]:
from math import inf

w_q= torch.Tensor([[-0.35, 0.51, 0.50],
                   [0.36, -0.47, -0.29],
                   [-0.51, -0.14, -0.56]]) #(dim_input , dim_output)
w_k= torch.Tensor([[-0.49, -0.68, 0.18],
                   [-0.44, -0.46, 0.18],
                   [0.07, -0.10, 0.44]])
w_v= torch.Tensor([[-0.41, 0.39, -0.65],
                   [-0.40, -0.07, -0.34],
                   [-0.55, -0.13, -0.29]])
w_o = torch.Tensor([[-0.36, -0.08, 0.32],
                    [0.27, 0.05, 0.15],
                    [-0.05, -0.28, 0.05]])

X = torch.Tensor([[-0.2, 0.0, 0.4]])
q= X@w_q
k= X@w_k
v= X@w_v
o= X@w_o
m= torch.Tensor([[0, -inf, -inf]])
score_raw= ((q@k.T)/d**0.5)
attn_weights = F.softmax(score_raw+m, dim=-1)
V_full = torch.cat([
    v,           # Dòng 1: Giá trị thật
    torch.zeros(1, 3),      # Dòng 2: Giả (bị mask che)
    torch.zeros(1, 3)       # Dòng 3: Giả (bị mask che)
], dim=0)

Y = attn_weights @ V_full
Y

tensor([[-0.1380, -0.1300,  0.0140]])

In [ ]:
w_q= torch.Tensor([[-0.35, 0.51, 0.50],
                   [0.36, -0.47, -0.29],
                   [-0.51, -0.14, -0.56]]) #(dim_input , dim_output)
w_k= torch.Tensor([[-0.49, -0.68, 0.18],
                   [-0.44, -0.46, 0.18],
                   [0.07, -0.10, 0.44]])
w_v= torch.Tensor([[-0.41, 0.39, -0.65],
                   [-0.40, -0.07, -0.34],
                   [-0.55, -0.13, -0.29]])
w_o = torch.Tensor([[-0.36, -0.08, 0.32],
                    [0.27, 0.05, 0.15],
                    [-0.05, -0.28, 0.05]])
w_q1= w_q
w_q2= -w_q
w_k1= w_k
w_k2= -w_k
w_v1= w_v
w_v2= -w_v

q1= X@w_q1
q2= X@w_q2

k1=X@w_k1
k2=X@w_k2

v1= X@w_v1
v2= X@w_v2

score_raw_1= (q1@k1.T)/d**0.5
attention_weight_1= F.softmax(score_raw_1, dim=-1)
context_1= attention_weight_1@v1

score_raw_2= (q2@k2.T)/d**0.5
attention_weight_2= F.softmax(score_raw_2, dim=-1)
context_2= attention_weight_2@v2


y= torch.cat([context_1, context_2], dim=1)
y

tensor([[-0.1380, -0.1300,  0.0140,  0.1380,  0.1300, -0.0140]])

In [ ]:
context_1

tensor([[-0.1380, -0.1300,  0.0140]])

In [ ]:
context_2

tensor([[ 0.1380,  0.1300, -0.0140]])

In [ ]:
from math import inf

w_q= torch.Tensor([[-0.35, 0.51, 0.50],
                   [0.36, -0.47, -0.29],
                   [-0.51, -0.14, -0.56]]) #(dim_input , dim_output)
w_k= torch.Tensor([[-0.49, -0.68, 0.18],
                   [-0.44, -0.46, 0.18],
                   [0.07, -0.10, 0.44]])
w_v= torch.Tensor([[-0.41, 0.39, -0.65],
                   [-0.40, -0.07, -0.34],
                   [-0.55, -0.13, -0.29]])
w_o = torch.Tensor([[-0.36, -0.08, 0.32],
                    [0.27, 0.05, 0.15],
                    [-0.05, -0.28, 0.05]])

X = torch.Tensor([[-0.1, 0.1, 0.3],
                  [0.4, -1.1, -0.3]])
q= X@w_q
k= X@w_k
v= X@w_v
o= X@w_o
m= torch.Tensor([[0, -inf],
                 [0, 0]])
score_raw= ((q@k.T)/d**0.5)


In [ ]:
v

tensor([[-0.1640, -0.0850, -0.0560],
        [ 0.4410,  0.2720,  0.2010]])

In [ ]:
attn_weights = F.softmax(score_raw+m, dim=-1)
attn_weights

tensor([[1.0000, 0.0000],
        [0.5220, 0.4780]])

In [ ]:
V_full = torch.cat([
    v,           # Dòng 1: Giá trị thật
    # torch.zeros(1, 3),     # Dòng 2: Giả (bị mask che)
    # torch.zeros(1, 3)      # Dòng 3: Giả (bị mask che)
], dim=0)

Y = attn_weights @ V_full
Y

tensor([[-0.1640, -0.0850, -0.0560],
        [ 0.1252,  0.0856,  0.0668]])

In [ ]:
import torch
import torch.nn.functional as F

# Inputs
X = torch.tensor([[-0.1, 0.1, 0.3],
                  [0.4, -1.1, -0.3]])
C = torch.tensor([[-0.6 ,0.3, -0.4],
                  [0.5, 0.9, -0.5]])

# Weights
W_Q = torch.tensor([[-0.35, 0.51, 0.50],
                    [0.36, -0.47, -0.29],
                    [-0.51, -0.14, -0.56]])
W_K = torch.tensor([[-0.49, -0.68, 0.18],
                    [-0.44, -0.46, 0.18],
                    [0.07, -0.10, 0.44]])
W_V = torch.tensor([[-0.41, 0.39, -0.65],
                    [-0.40, -0.07, -0.34],
                    [-0.55, -0.13, -0.29]])
W_O = torch.tensor([[-0.36, -0.08, 0.32],
                    [0.27, 0.05, 0.15],
                    [-0.05, -0.28, 0.05]])

d = 3.0

# Case 1: Standard Cross Attention (Q from X, K/V from C)
Q = X @ W_Q
K = C @ W_K
V = C @ W_V
scores = (Q @ K.T) / (d**0.5)
attn = F.softmax(scores, dim=-1)
context = attn @ V
Y_standard = context @ W_O

# Case 2: Swapped Cross Attention (Q from C, K/V from X)
Q2 = C @ W_Q
K2 = X @ W_K
V2 = X @ W_V
scores2 = (Q2 @ K2.T) / (d**0.5)
attn2 = F.softmax(scores2, dim=-1)
context2 = attn2 @ V2
Y_swapped = context2 @ W_O

print("Standard Result (Q=X, K=C):")
print(Y_standard)
print("Rounded Standard:")
print(torch.round(Y_standard * 100) / 100)

print("\nSwapped Result (Q=C, K=X):")
print(Y_swapped)

Standard Result (Q=X, K=C):
tensor([[-0.0009,  0.0157,  0.0026],
        [-0.0244, -0.0040,  0.0141]])
Rounded Standard:
tensor([[-0.0000,  0.0200,  0.0000],
        [-0.0200, -0.0000,  0.0100]])

Swapped Result (Q=C, K=X):
tensor([[-0.0298, -0.0279,  0.0651],
        [-0.0276, -0.0262,  0.0607]])
